### ISSUE TITLE
Will the coverage upload be skipped only if `--skip` or `-s` is passed in?

### ISSUE THREAD

**Issue by valeriupredoi** [codacy/codacy-coverage-reporter#500]
Hi folks, wuick question please (sorry I got rid of the Issue template - too much faff for such a simple question): we are using the codacy cov uploader via CircleCI as orb ie:

```yaml
orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.5
  codecov: codecov/codecov@3.2.5
```

and noticed that the coverage upload is not skipped if the PR is from a forked repo (so the project API token is missing there), and fails with the obvious "project token missing" - do we have to explicitly have the `--skip` option turned on to allow for a skip in this case, and avoid a fail? Many thanks in advance! Cheers muchly :beers:

**Comment by lolgab** [comment]
Hi @valeriupredoi!
You can use the [`skip` parameter](https://github.com/codacy/codacy-coverage-reporter/blob/master/orbs/commands/send_report.yml#L16-L19):
```
orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.5
  codecov: codecov/codecov@3.2.5
  skip: true
```
